server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: yhx123456
    driver-class-name: com.mysql.cj.jdbc.Driver
      # 配置Druid数据库
  type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 20 # 初始连接数
    min-idle: 10 # 最小空闲连接数
    max-active: 100 # 最大连接数
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  #  开发阶段不持久化日志，debug模式可以看sql
  #  file:
  #    path: E:\\FinishDesigning\\log
  #    name: job.log
  level:
    com.job: debug